---
ID: "f68a527d-bb75-42c5-8d50-e94ec77c2418"
Parent: "459a089a-a654-4cae-be75-d96a0300daf9"
Template: "52288e39-7830-4694-b62d-32a54c6ef7ba"
Path: /sitecore/content/demo site collection/xmcvara/Presentation/Placeholder Settings
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230525T151216Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\varalakshmi.md@horizontal.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\varalakshmi.md@horizontal.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "f1c64512-9ced-4854-8934-840f2e8bf9c1"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\varalakshmi.md@horizontal.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230525T151216Z
