---
ID: "319ee1c2-7d04-4fb6-84bb-68b30cd8eb0a"
Parent: "9d1e0d3d-1516-4e7d-ac6e-e2b45a0e0be8"
Template: "1105b8f8-1e00-426b-bf1f-c840742d827b"
Path: /sitecore/content/demo site collection/xmcvara/Presentation/Page Designs/Default
SharedFields:
- ID: "0966b999-0d0e-4278-acc9-9da69d461fe6"
  Hint: PartialDesigns
  Value: "{F0070D60-B1F9-4A61-8DC8-1A357410A74A}|{231E81B2-2CE6-4F97-B04D-6F10176B81F2}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230525T151224Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\varalakshmi.md@horizontal.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\varalakshmi.md@horizontal.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "2e64383d-a21c-4dfb-a05c-4c4e5b74b265"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\varalakshmi.md@horizontal.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230525T151227Z
